<?xml version="1.0" encoding="UTF-8"?>
<!-- You may freely edit this file. See commented blocks below for -->
<!-- some examples of how to customize the build.                   -->
<project name="FlowBankA3" default="default" basedir=".">
    <description>Builds, tests, and runs the project FlowBankA3.</description>
    <import file="nbproject/build-impl.xml"/>
</project>
